let servicesData=[];let filteredCategory='';async function loadServices(){const res=await fetch('services.json');servicesData=await res.json();buildCategoryChips();renderServices();populateServiceSelect();}
function buildCategoryChips(){const categories=[...new Set(servicesData.map(s=>s.category))];const chips=document.getElementById('categoryChips');chips.innerHTML='';categories.forEach(cat=>{const chip=document.createElement('span');chip.className='chip';chip.textContent=cat;chip.onclick=()=>{filteredCategory=(filteredCategory===cat?'':cat);document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));if(filteredCategory)chip.classList.add('active');renderServices();};chips.appendChild(chip);});}
function renderServices(){const list=document.getElementById('servicesList');list.innerHTML='';const query=document.getElementById('searchInput').value.toLowerCase();servicesData.filter(s=>(!filteredCategory||s.category===filteredCategory)&&(s.service.toLowerCase().includes(query)||s.desc.toLowerCase().includes(query))).forEach(service=>{const card=document.createElement('div');card.className='service-card';card.innerHTML=`<h3>${service.service}</h3><p>${service.desc}</p><div class="price">PKR ${service.price} / 1000</div><button data-id="${service.id}">Select</button>`;card.querySelector('button').onclick=()=>{selectServiceById(service.id);window.location.hash='#order';};list.appendChild(card);});}
function populateServiceSelect(){const select=document.getElementById('serviceSelect');select.innerHTML='<option value="" disabled selected>Select service</option>';servicesData.forEach(s=>{const opt=document.createElement('option');opt.value=s.id;opt.textContent=`${s.service} (PKR ${s.price}/1000)`;select.appendChild(opt);});}
function selectServiceById(id){document.getElementById('serviceSelect').value=id;onServiceChange();}
function onServiceChange(){const select=document.getElementById('serviceSelect');const qtyInput=document.getElementById('quantityInput');const priceInfo=document.getElementById('priceInfo');const etaInfo=document.getElementById('etaInfo');const sticky=document.getElementById('stickyBar');const stickyService=document.getElementById('stickyService');const stickyPrice=document.getElementById('stickyPrice');const sel=servicesData.find(s=>s.id===select.value);if(!sel){sticky.classList.add('hidden');priceInfo.textContent='Total: PKR 0';etaInfo.textContent='ETA: –';qtyInput.value='';return;}qtyInput.min=sel.min;qtyInput.max=sel.max;qtyInput.placeholder=`${sel.min} - ${sel.max}`;function recalc(){let qty=parseInt(qtyInput.value,10)||sel.min;qty=Math.max(sel.min,Math.min(sel.max,qty));const total=((qty/1000)*sel.price).toFixed(0);const eta=Math.ceil((qty/sel.min)*sel.avg);priceInfo.textContent=`Total: PKR ${total}`;etaInfo.textContent=`ETA: ${eta} min`;stickyService.textContent=`${sel.service} × ${qty}`;stickyPrice.textContent=`PKR ${total}`;sticky.classList.remove('hidden');}recalc();qtyInput.oninput=recalc;}
function validateLink(link){return /^(https?:\/\/)?([\w.-]+)\.[a-z]{2,}.*$/i.test(link)||/^@?\w{3,}$/.test(link);}
function setupOrderForm(){const select=document.getElementById('serviceSelect');select.addEventListener('change',onServiceChange);document.getElementById('orderForm').addEventListener('submit',async e=>{e.preventDefault();const sel=servicesData.find(s=>s.id===select.value);const qty=parseInt(document.getElementById('quantityInput').value,10);const link=document.getElementById('linkInput').value.trim();if(!sel){alert('Please select a service');return;}if(isNaN(qty)||qty<sel.min||qty>sel.max){alert(`Quantity must be between ${sel.min} and ${sel.max}`);return;}if(!validateLink(link)){alert('Please enter a valid link or username');return;}const total=((qty/1000)*sel.price).toFixed(0);const eta=Math.ceil((qty/sel.min)*sel.avg);const pageUrl=window.location.href;const msg=`Service: ${sel.service}\nQty: ${qty}\nLink: ${link}\nPrice: PKR ${total}\nETA: ${eta} min\nURL: ${pageUrl}`;const waUrl=`https://wa.me/923193840214?text=${encodeURIComponent(msg)}`;const payload={ts:new Date().toISOString(),name:sel.service,link:link,qty:qty,serviceId:sel.id,price:total,eta:eta,status:'pending'};try{await fetch('YOUR_APPS_SCRIPT_URL',{method:'POST',body:JSON.stringify(payload),headers:{'Content-Type':'application/json'}});}catch(err){console.warn('Order logging failed',err);}window.open(waUrl,'_blank');});}
function setupStickyBar(){document.getElementById('stickyButton').addEventListener('click',()=>{document.getElementById('orderForm').dispatchEvent(new Event('submit',{cancelable:true}));});}
function setupExitIntent(){let shown=false;const modal=document.getElementById('exitModal');const submit=document.getElementById('leadSubmit');const close=document.getElementById('leadClose');const numberInput=document.getElementById('leadNumber');function show(){if(shown)return;shown=true;modal.classList.remove('hidden');}function hide(){modal.classList.add('hidden');}document.addEventListener('mouseout',e=>{if(e.clientY<0)show();});history.pushState({},'');window.addEventListener('popstate',e=>{show();history.pushState({},'');});close.onclick=hide;submit.onclick=async ()=>{const number=numberInput.value.trim();if(!number)return;const payload={ts:new Date().toISOString(),number:number,status:'lead'};try{await fetch('YOUR_APPS_SCRIPT_URL',{method:'POST',body:JSON.stringify(payload),headers:{'Content-Type':'application/json'}});}catch(err){console.warn('Lead logging failed',err);}hide();};}
function setupSearch(){document.getElementById('searchInput').addEventListener('input',renderServices);}
document.addEventListener('DOMContentLoaded',()=>{loadServices();setupOrderForm();setupStickyBar();setupExitIntent();setupSearch();});
